### ISSUE TITLE
`noble_1.default.removeAllListeners is not a function`: boot loop

### ISSUE THREAD

**Issue by gorillica** [howm/homebridge-vogels-motionmount#238]
Hi, I've just tried to install `homebridge-vogels-motionmount`, and I get the error `noble_1.default.removeAllListeners is not a function` upon Homebridge restart. Then Homebridge enters a boot loop until I remove the plugin. Any suggestions for how I could fix this? Thanks!

 ```
TypeError: noble_1.default.removeAllListeners is not a function
    at detectFirstMotionMountPeripheral (/var/lib/homebridge/node_modules/homebridge-vogels-motionmount/helper/motionMount.js:17:21)
    at getPeripheral (/var/lib/homebridge/node_modules/homebridge-vogels-motionmount/helper/motionMount.js:37:36)
    at Object.retrievePositionPresets (/var/lib/homebridge/node_modules/homebridge-vogels-motionmount/helper/motionMount.js:64:30)
    at MotionMountDynamicPlatform.updateInputs (/var/lib/homebridge/node_modules/homebridge-vogels-motionmount/platform/MotionMountDynamicPlatform.js:73:53)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vogels-motionmount/platform/MotionMountDynamicPlatform.js:21:24)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:190:14)
```

**Comment by momsse** [comment]
Hi, didn't use that plugin since a while since bluetooth latency with my raspberry was an issue on my side. I'm trying a v2 with faster connection to the device. Still in alpha for now (will try it first before releasing the "stable" one)
