### ISSUE TITLE
No selector for different positions: scan failure

### ISSUE THREAD

**Issue by mmralser** [howm/homebridge-vogels-motionmount#76]
I only see an On/Off Button, no selector for different positions. I have the NEXT 7365 MotionMount and I have Homebridge running on a Mac Mini 2019. 

Great seeing someone work with MotionMount at all, big love to you from Germany <3

> [4/11/2021, 2:42:56 AM] [MotionMount] [moveToPosition] Going to Wall
[4/11/2021, 2:42:56 AM] [MotionMount] [getPeripheral] Detecting peripheral ...
[4/11/2021, 2:42:56 AM] [MotionMount] [detectFirstMotionMountPeripheral] Removing discover listeners
[4/11/2021, 2:42:56 AM] [MotionMount] [detectFirstMotionMountPeripheral] Starting scan
[4/11/2021, 2:42:56 AM] [MotionMount] [detectFirstMotionMountPeripheral] scan failure
(node:5218) UnhandledPromiseRejectionWarning: Error: Could not start scanning, state is unknown (not poweredOn)
    at Noble.scan (/usr/local/lib/node_modules/homebridge-vogels-motionmount/node_modules/@abandonware/noble/lib/noble.js:120:21)
    at Noble.startScanning (/usr/local/lib/node_modules/homebridge-vogels-motionmount/node_modules/@abandonware/noble/lib/noble.js:149:10)
    at /usr/local/lib/node_modules/homebridge-vogels-motionmount/node_modules/@abandonware/noble/lib/noble.js:155:44
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at internal/util.js:296:12
    at Noble.startScanningAsync (/usr/local/lib/node_modules/homebridge-vogels-motionmount/node_modules/@abandonware/noble/lib/noble.js:155:99)
    at /usr/local/lib/node_modules/homebridge-vogels-motionmount/helper/motionMount.js:26:14
    at new Promise (<anonymous>)
    at detectFirstMotionMountPeripheral (/usr/local/lib/node_modules/homebridge-vogels-motionmount/helper/motionMount.js:18:12)
(node:5218) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)

![IMG_2994](https://user-images.githubusercontent.com/76612541/114288483-944cae00-9a70-11eb-8326-1dc3fa916f56.PNG)

**Comment by momsse** [comment]
Hello,

Sorry for the delay, given the log it seems that `noble` the library used behind does not detect the bluetooth of your homebridge as powered on.

```
(node:5218) UnhandledPromiseRejectionWarning: Error: Could not start scanning, state is unknown (not poweredOn)
```

Check if the bluetooth is correctly set on your Mac mini and if so try to reboot your homebridge device afterward. Good luck to you
